# Generated by Django 4.2 on 2023-04-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
