# Generated by Django 4.1.7 on 2023-04-09 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='media files')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prep_time', models.IntegerField(blank=True, default=0, null=True)),
                ('cook_time', models.IntegerField(blank=True, default=0, null=True)),
                ('serving', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('like_num', models.IntegerField(blank=True, default=0, null=True)),
                ('overall_rating', models.FloatField(blank=True, default=0, null=True)),
                ('rating_num', models.IntegerField(blank=True, default=0, null=True)),
                ('added', models.ManyToManyField(blank=True, related_name='added', to=settings.AUTH_USER_MODEL)),
                ('base_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.recipe')),
                ('comment_list', models.ManyToManyField(blank=True, related_name='comment_list', to='recipe.comment')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.cuisine')),
                ('diets', models.ManyToManyField(blank=True, to='recipe.diet')),
                ('ingredients', models.ManyToManyField(blank=True, to='recipe.ingredient')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('media_list', models.ManyToManyField(blank=True, related_name='recipe_media_list', to='recipe.media')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('media_list', models.ManyToManyField(blank=True, related_name='step_media_list', to='recipe.media')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.step')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('recipe', 'order')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='step_list',
            field=models.ManyToManyField(blank=True, through='recipe.RecipeStep', to='recipe.step'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
