# Generated by Django 4.2 on 2023-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment_list',
            field=models.ManyToManyField(blank=True, related_name='recipe_set', to='recipe.comment'),
        ),
    ]
