# Generated by Django 4.0.2 on 2023-04-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_comment_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment_list',
            field=models.ManyToManyField(blank=True, related_name='recipe_set', to='recipe.Comment'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, to='recipe.Diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='media_list',
            field=models.ManyToManyField(blank=True, related_name='recipe_media_list', to='recipe.Media'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step_list',
            field=models.ManyToManyField(blank=True, through='recipe.RecipeStep', to='recipe.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='media_list',
            field=models.ManyToManyField(blank=True, related_name='step_media_list', to='recipe.Media'),
        ),
    ]
